micronaut:
  application:
    name: auth

  server:
    cors:
      enabled: true

  security:
    enabled: true
    authentication: idtoken
    intercept-url-map:
      - pattern: /public/**
        http-method: GET
        access:
          - isAnonymous()

  router:
    static-resources:
      default:
        enabled: true
        mapping: /public/**
        paths: 'classpath:public'

netty:
  default:
    allocator:
      max-order: 3
