micronaut:
  application:
    name: auth

  server:
    cors:
      enabled: true

  security:
    enabled: true
    authentication: idtoken
    redirect:
      enabled: false
    intercept-url-map:
      - pattern: /public/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        http-method: GET
        access:
          - isAnonymous()

  router:
    static-resources:
      default:
        mapping: /public/**
        paths: 'classpath:public'
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

netty:
  default:
    allocator:
      max-order: 3
