micronaut:
  application:
    name: auth

  server:
    cors:
      enabled: true

  security:
    enabled: false

  router:
    static-resources:
      default:
        enabled: true
        mapping: /public/**
        paths: 'classpath:public'
netty:
  default:
    allocator:
      max-order: 3
