micronaut:
  application:
    name: auth

  server:
    cors:
      enabled: true

  security:
    enabled: true
    authentication: idtoken
    intercept-url-map:
      - pattern: /public/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()

  router:
    static-resources:
      default:
        mapping: /public/**
        paths: 'classpath:public'
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

netty:
  default:
    allocator:
      max-order: 3
