# This configuration contains a default configuration allowing to start SympAuhty with minimal
# additional configurations.

advanced:
  authorization-flow:
    expiration: 30m
  hash:
    block-size: 8
    cost-parameter: 16_384
    key-length: 32
    parallelization-parameter: 1
    salt-length: 256
  jwt:
    public-alg: rs256
    access-alg: rs256
    private-alg: rs256
  keys-generation-strategy: autoincrement
  validation-code:
    length: 6
    resend-delay: 1m
    expiration: 10m

auth:
  user-merging-enabled: false
  token:
    access-expiration: 1h
    refresh-enabled: true
    refresh-expiration: 30d
    dpop-required: false

clients:
  default:
    default-scopes:
      - openid
      - profile
    flow: default

mfa:
  required: false
  totp:
    enabled: false

features:
  allow-access-to-client-without-scope: false
  email-validation: false
  grant-unhandled-scopes: false
  print-details-in-error: false

ui:
  display-name: SympAuthy
  mail:
    email-background-color: "#f3f3f5"
    primary-color: ""
    background-color: "#ffffff"
    on-primary-color: ""
    on-background-color: "#3C3F44"
