# This configuration contains a default configuration allowing to start SympAuhty with minimal
# additional configurations.

advanced:
  authorization-webhook:
    timeout: 5s
  hash:
    block-size: 8
    cost-parameter: 16_384
    key-length: 32
    parallelization-parameter: 1
    salt-length: 256
  jwt:
    public-alg: es256
    access-alg: es256
    private-alg: es256
  keys-generation-strategy: autoincrement
  validation-code:
    length: 6
    resend-delay: 1m
    expiration: 10m

auth:
  authorization-code:
    expiration: 30m
  user-merging-enabled: false
  token:
    access-expiration: 1h
    refresh-enabled: true
    refresh-expiration: 30d
    dpop-required: false

templates:
  claims:
    default:
      acl:
        readable-with-client-scopes-unconditionally:
          - "users:claims:read"
        writable-with-client-scopes-unconditionally:
          - "users:claims:write"
    openid:
      enabled: "false"
      acl:
        readable-by-user-when-consented: "true"
        writable-by-user-when-consented: "true"
        readable-by-client-when-consented: "true"
        writable-by-client-when-consented: "false"
  clients:
    default:
      default-scopes:
        - openid
        - profile
      flow: default
      allowed-grant-types:
        - authorization_code
        - refresh_token
        - client_credentials

claims:
  sub:
    template: openid
    type: string
  name:
    template: openid
    type: string
  given_name:
    template: openid
    type: string
  family_name:
    template: openid
    type: string
  middle_name:
    template: openid
    type: string
  nickname:
    template: openid
    type: string
  preferred_username:
    template: openid
    type: string
  profile:
    template: openid
    type: string
  picture:
    template: openid
    type: string
  website:
    template: openid
    type: string
  email:
    template: openid
    type: email
  gender:
    template: openid
    type: string
  birth_date:
    template: openid
    type: date
  zoneinfo:
    template: openid
    type: timezone
  locale:
    template: openid
    type: string
  phone_number:
    template: openid
    type: phone_number
  updated_at:
    template: openid
    type: string
  street_address:
    template: openid
    type: string
  locality:
    template: openid
    type: string
  region:
    template: openid
    type: string
  postal_code:
    template: openid
    type: string
  country:
    template: openid
    type: string

mfa:
  required: false
  totp:
    enabled: false

features:
  allow-access-to-client-without-scope: false
  email-validation: false
  grant-unhandled-scopes: false
  print-details-in-error: false

ui:
  display-name: SympAuthy
  mail:
    email-background-color: "#f3f3f5"
    primary-color: ""
    background-color: "#ffffff"
    on-primary-color: ""
    on-background-color: "#3C3F44"
