# This configuration contains a default configuration allowing to start SympAuhty with minimal
# additional configurations.

advanced:
  hash:
    block-size: 8
    cost-parameter: 16_384
    key-length: 32
    parallelization-parameter: 1
    salt-length: 256
  jwt:
    public-alg: rs256
    private-alg: rs256
  keys-generation-strategy: autoincrement
  user-merging-strategy: by-mail

auth:
  token:
    access-expiration: 1h
    refresh-enabled: true
    refresh-expiration: 30d

authentication-flows:
  default:
    type: web
    sign-in: sign-in
    collect-claims: collect-claims
    validation-code: validation-code
    error: error

scope-granting-rules:
  default:
    scopes:
      - openid
      - profile
    rules:
      - anyUser

ui:
  mail:
    email-background-color: "#f3f3f5"
    primary-color: ""
    background-color: "#ffffff"
    on-primary-color: ""
    on-background-color: "#3C3F44"
