# Configuration allowing end-user to sign in/sign up using their email.
# It also enables validation of email and therefore requires an SMTP to be configured using javamail.
#
# Can be enabled by appending 'mail' to the Micronaut environments.

claims:
  email:
    enabled: true

templates:
  clients:
    default:
      default-scopes:
        - openid
        - profile
        - email

features:
  email-validation: true

javamail:
  enabled: true

auth:
  user-merging-enabled: true
  identifier-claims:
    - email
  by-password:
    enabled: true
