# Default configuration for Google as a third-party OpenID Connect provider.
#
# Enable this preset by adding "google" to the MICRONAUT_ENVIRONMENTS variable, and supply the
# client credentials it leaves unset. They are obtained by following:
# https://developers.google.com/identity/openid-connect/openid-connect

providers:
  google:
    name: Google
    oidc:
      issuer: https://accounts.google.com
      scopes:
        - openid
        - email
        - profile
