# This application.yml provides configuration only for the Micronaut server.
# It does not provide any default value for the SympAuthy configuration.
# This is done to easily disable the default configuration of SympAuthy.
# Enable default profile using Micronaut environments: https://docs.micronaut.io/latest/guide/#environments

micronaut:
  application:
    name: sympauthy

  server:
    cors:
      enabled: false

  security:
    enabled: true
    authentication: idtoken
    redirect:
      enabled: false
    intercept-url-map:
      - pattern: /flow/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        http-method: GET
        access:
          - isAnonymous()

  router:
    static-resources:
      flow-non-html:
        paths: classpath:sympauthy-flow
        mapping: /flow/*.ico
      flow-assets:
        paths: classpath:sympauthy-flow/assets
        mapping: /flow/assets/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

netty:
  default:
    allocator:
      max-order: 3

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: anonymous
    disk-space:
      enabled: false
    jdbc:
      enabled: false

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - filesystem:./databases

# Disable otherwise JavaMailConfiguration is created empty, which causes problems to detect if mails are in-fact enabled.
# As soon as it is enabled, it will cause the application to fail with the following message if the rest of the
# configuration is absent: JavaMail configuration does not contain any properties.
javamail:
  enabled: false
