package com.sympauthy.business.model.user.claim

sealed class Claim(
    /**
     * Identifier of the claim.
     */
    val id: String,
    /**
     * Whether the claim is enabled on this authorization server.
     */
    val enabled: Boolean,
    /**
     * Identifier of the claim indicating the value of this claims has been verified by the authorization server.
     * Ex. email_verified for the standard email claim.
     */
    val verifiedId: String?,
    /**
     * Type of the claim.
     */
    val dataType: ClaimDataType,
    /**
     * Optional group this claim belongs to (ex. identity, address).
     * Groups are used to organize claims when presenting them to the end-user during authentication flows.
     */
    val group: ClaimGroup?,
    /**
     * True if the end-user MUST provide a value for this claim before completing any authentication flow
     * (either password or third-party providers).
     */
    val required: Boolean,
    /**
     * Should the claim be collected from end-user input during authenticated flow or its value is managed
     * by another mean (generated by server, managed by a client through API, etc.)?
     */
    val userInputted: Boolean,
    /**
     * List of values that are allowed.
     * If null, all values are accepted by this authorization server.
     */
    val allowedValues: List<Any>?
) {

    /**
     * Return true if this claim is covered by the given [scope].
     */
    abstract fun belongsToScope(scope: String): Boolean

    /**
     * Return true if the end-user can read this claim given the consented [scopes].
     */
    abstract fun canBeReadByUser(scopes: List<String>): Boolean

    /**
     * Return true if the end-user can write this claim given the consented [scopes].
     */
    abstract fun canBeWrittenByUser(scopes: List<String>): Boolean

    /**
     * Return true if a client can read this claim given the consented [scopes].
     */
    abstract fun canBeReadByClient(scopes: List<String>): Boolean

    /**
     * Return true if a client can write this claim given the consented [scopes].
     */
    abstract fun canBeWrittenByClient(scopes: List<String>): Boolean
}

enum class ClaimOrigin(val value: String) {
    OPENID("openid"),
    CUSTOM("custom")
}

val Claim.origin: ClaimOrigin
    get() = when (this) {
        is StandardClaim -> ClaimOrigin.OPENID
        is CustomClaim -> ClaimOrigin.CUSTOM
    }
