package com.sympauthy.business.model.user.claim

import com.sympauthy.util.PublishedUnderAnotherName
import java.time.Duration
import java.time.LocalDateTime

/**
 * A claim configured on this authorization server.
 *
 * Claims can originate from the OpenID Connect specification ([ClaimOrigin.OPENID_CONNECT]) or be
 * custom claims defined by the operator ([ClaimOrigin.CUSTOM]). Access control is determined by the
 * [acl] and the [kind] rather than the claim origin.
 */
data class Claim(
    /**
     * Identifier of the claim.
     */
    val id: String,
    /**
     * Whether the claim is enabled on this authorization server.
     */
    val enabled: Boolean,
    /**
     * Identifier of the claim indicating the value of this claims has been verified by the authorization server.
     * Ex. email_verified for the standard email claim.
     */
    val verifiedId: String?,
    /**
     * Type of the claim.
     */
    val dataType: ClaimDataType,
    /**
     * Optional group this claim belongs to (ex. identity, address).
     * Groups are used to organize claims when presenting them to the end-user during authentication flows.
     */
    val group: ClaimGroup?,
    /**
     * True if the end-user MUST provide a value for this claim before completing any authentication flow
     * (either password or third-party providers).
     */
    val required: Boolean,
    /**
     * Whether the claim value is generated by the authorization server (e.g. `sub`, `updated_at`).
     */
    val generated: Boolean,
    /**
     * Should the claim be collected from end-user input during authenticated flow or its value is managed
     * by another mean (generated by server, managed by a client through API, etc.)?
     *
     * Derived from: `!generated && acl.consent.collectedInFlow`.
     */
    val collectedInFlow: Boolean,
    /**
     * List of values that are allowed.
     * If null, all values are accepted by this authorization server.
     */
    val allowedValues: List<Any>?,
    /**
     * Whose this claim's value is, or null where it is nobody's to write because this server computes
     * it — which, in a configuration that started, is every [generated] claim and only those.
     *
     * The [acl] is held to it at startup rather than at request time: a personal claim restricted to
     * no audience grants no client write, and an application claim grants neither of the person's.
     */
    val kind: ClaimKind?,
    /**
     * Identifier of the audience this claim is restricted to.
     * When null, the claim is shared across all audiences.
     */
    val audienceId: String? = null,
    /**
     * The places this claim is published in.
     *
     * Publication is not permission: these narrow what [acl] already allows, and a claim naming no place
     * is still read through the client, admin and user APIs, which the ACL alone gates.
     */
    val publishedIn: Set<ClaimPublicationPlace>,
    /**
     * Access control list determining who can read/write this claim and under what conditions.
     */
    val acl: ClaimAcl
) {

    /**
     * Origin of this claim, derived from whether the [id] matches a known OpenID Connect claim.
     */
    val origin: ClaimOrigin
        get() = if (id in OpenIdConnectClaimId.ALL) ClaimOrigin.OPENID_CONNECT else ClaimOrigin.CUSTOM

    /**
     * Return true if this claim is covered by the given [scope].
     */
    fun belongsToScope(scope: String): Boolean = acl.consent.scope == scope

    /**
     * Return true if this claim is one the audience identified by [audienceId] has: either it is restricted to
     * no audience, or it is restricted to that one.
     *
     * This is the whole of the [audienceId] restriction, and it is asked apart from the ACL rather than inside
     * it: what an audience has is a different question from what a caller may read, and a claim may have to be
     * tested for the first where no scope applies — the set of required claims a flow computes is one.
     */
    fun belongsToAudience(audienceId: String): Boolean =
        this.audienceId == null || this.audienceId == audienceId

    /**
     * Return true if this claim is published in [place].
     *
     * This narrows and never grants, so a caller asks it beside the permission test rather than instead
     * of one: a claim the ACL refuses is published in no place whatever this says.
     */
    fun isPublishedIn(place: ClaimPublicationPlace): Boolean = place in publishedIn

    /**
     * Return true if the person can read this claim through their own access token, given the
     * [consentedScopes].
     *
     * Access is granted when [ConsentAcl.readableByPerson] is true AND either no consent scope
     * is configured on this claim, or the person has consented to it.
     */
    fun canBeReadByPerson(consentedScopes: List<String>): Boolean =
        acl.consent.readableByPerson && (acl.consent.scope == null || acl.consent.scope in consentedScopes)

    /**
     * Return true if the interactive flow collects this claim from the person, given the
     * [consentedScopes].
     *
     * Access is granted when [ConsentAcl.collectedInFlow] is true AND either no consent scope
     * is configured on this claim, or the person has consented to it. It is the flow's permission
     * alone, and [canBeWrittenByPerson] is the one a person's own access token writes through.
     *
     * An identifier claim answers from the flag like any other, and the flow reaches this for none of what
     * it does with one: [ConsentAcl.collectedInFlow] says why.
     */
    fun isCollectedInFlow(consentedScopes: List<String>): Boolean =
        acl.consent.collectedInFlow && (acl.consent.scope == null || acl.consent.scope in consentedScopes)

    /**
     * Return true if the person's own access token can write this claim, given the [consentedScopes].
     *
     * Access is granted when [ConsentAcl.writableByPerson] is true AND either no consent scope is
     * configured on this claim, or the person has consented to it. It is a separate permission from
     * [isCollectedInFlow], which is the flow's: see [ConsentAcl.writableByPerson].
     *
     * It says nothing about how recently the person authenticated, which
     * [isAuthenticationRecentEnough] answers beside it.
     */
    fun canBeWrittenByPerson(consentedScopes: List<String>): Boolean =
        acl.consent.writableByPerson &&
                (acl.consent.scope == null || acl.consent.scope in consentedScopes)

    /**
     * Return true if an authentication dated [authenticationTime] is recent enough, at [now], for a write
     * of this claim through the person's own access token.
     *
     * A claim declaring no maximum age asks nothing and answers true whatever [authenticationTime] is,
     * including null. A claim declaring one answers false for a token stating no authentication time at
     * all: such a token has no person's authentication behind it — a client-credentials grant, a token
     * exchange — and a claim asking for a recent one is not answered by a token that proves none.
     *
     * A caller refused here owes the client the challenge RFC 9470 defines, carrying
     * [ConsentAcl.writeMaxAuthenticationAge] as its `max_age`, rather than a bare refusal: the client can
     * re-authorize and retry, and the challenge is what tells it so.
     */
    fun isAuthenticationRecentEnough(
        authenticationTime: LocalDateTime?,
        now: LocalDateTime = LocalDateTime.now()
    ): Boolean {
        val maxAge = acl.consent.writeMaxAuthenticationAge ?: return true
        if (authenticationTime == null) return false
        return Duration.between(authenticationTime, now) <= maxAge
    }

    /**
     * Return true if a client can read this claim given the [consentedScopes] and [clientScopes].
     *
     * Access is granted through either path:
     * - **Consent path**: [ConsentAcl.readableByClient] is true AND either no consent scope
     *   is configured on this claim, or the end-user has consented to it.
     * - **Unconditional path**: the client holds any scope in [clientScopes] listed in
     *   [UnconditionalAcl.readableWithClientScopes], regardless of end-user consent.
     */
    fun canBeReadByClient(consentedScopes: List<String>, clientScopes: List<String>): Boolean =
        (acl.consent.readableByClient && (acl.consent.scope == null || acl.consent.scope in consentedScopes)) ||
                clientScopes.any { it in acl.unconditional.readableWithClientScopes }

    /**
     * Return true if a client can write this claim given the [consentedScopes] and [clientScopes].
     *
     * Access is granted through either path:
     * - **Consent path**: [ConsentAcl.writableByClient] is true AND either no consent scope
     *   is configured on this claim, or the end-user has consented to it.
     * - **Unconditional path**: the client holds any scope in [clientScopes] listed in
     *   [UnconditionalAcl.writableWithClientScopes], regardless of end-user consent.
     */
    fun canBeWrittenByClient(consentedScopes: List<String>, clientScopes: List<String>): Boolean =
        (acl.consent.writableByClient && (acl.consent.scope == null || acl.consent.scope in consentedScopes)) ||
                clientScopes.any { it in acl.unconditional.writableWithClientScopes }
}

enum class ClaimOrigin(
    override val publishedName: String? = null
) : PublishedUnderAnotherName {
    /**
     * Published as `openid`, the word the OpenID Connect specification uses for the claims it
     * defines, rather than the `openid_connect` this value's name spells.
     */
    OPENID_CONNECT("openid"),
    CUSTOM
}
