package com.sympauthy.business.model.user.claim

/**
 * A claim configured on this authorization server.
 *
 * Claims can originate from the OpenID Connect specification ([ClaimOrigin.OPENID_CONNECT]) or be
 * custom claims defined by the operator ([ClaimOrigin.CUSTOM]). Access control is determined
 * by the [acl] rather than the claim origin.
 */
data class Claim(
    /**
     * Identifier of the claim.
     */
    val id: String,
    /**
     * Whether the claim is enabled on this authorization server.
     */
    val enabled: Boolean,
    /**
     * Identifier of the claim indicating the value of this claims has been verified by the authorization server.
     * Ex. email_verified for the standard email claim.
     */
    val verifiedId: String?,
    /**
     * Type of the claim.
     */
    val dataType: ClaimDataType,
    /**
     * Optional group this claim belongs to (ex. identity, address).
     * Groups are used to organize claims when presenting them to the end-user during authentication flows.
     */
    val group: ClaimGroup?,
    /**
     * True if the end-user MUST provide a value for this claim before completing any authentication flow
     * (either password or third-party providers).
     */
    val required: Boolean,
    /**
     * Whether the claim value is generated by the authorization server (e.g. `sub`, `updated_at`).
     */
    val generated: Boolean,
    /**
     * Should the claim be collected from end-user input during authenticated flow or its value is managed
     * by another mean (generated by server, managed by a client through API, etc.)?
     *
     * Derived from: `!generated && acl.consent.writableByUser`.
     */
    val userInputted: Boolean,
    /**
     * List of values that are allowed.
     * If null, all values are accepted by this authorization server.
     */
    val allowedValues: List<Any>?,
    /**
     * Access control list determining who can read/write this claim and under what conditions.
     */
    val acl: ClaimAcl
) {

    /**
     * Origin of this claim, derived from whether the [id] matches a known OpenID Connect claim.
     */
    val origin: ClaimOrigin
        get() = if (id in OpenIdConnectClaimId.ALL) ClaimOrigin.OPENID_CONNECT else ClaimOrigin.CUSTOM

    /**
     * Return true if this claim is covered by the given [scope].
     */
    fun belongsToScope(scope: String): Boolean = acl.consent.scope == scope

    /**
     * Return true if the end-user can read this claim given the [consentedScopes].
     *
     * Access is granted when [ConsentAcl.readableByUser] is true AND either no consent scope
     * is configured on this claim, or the end-user has consented to it.
     */
    fun canBeReadByUser(consentedScopes: List<String>): Boolean =
        acl.consent.readableByUser && (acl.consent.scope == null || acl.consent.scope in consentedScopes)

    /**
     * Return true if the end-user can write this claim given the [consentedScopes].
     *
     * Access is granted when [ConsentAcl.writableByUser] is true AND either no consent scope
     * is configured on this claim, or the end-user has consented to it.
     */
    fun canBeWrittenByUser(consentedScopes: List<String>): Boolean =
        acl.consent.writableByUser && (acl.consent.scope == null || acl.consent.scope in consentedScopes)

    /**
     * Return true if a client can read this claim given the [consentedScopes] and [clientScopes].
     *
     * Access is granted through either path:
     * - **Consent path**: [ConsentAcl.readableByClient] is true AND either no consent scope
     *   is configured on this claim, or the end-user has consented to it.
     * - **Unconditional path**: the client holds any scope in [clientScopes] listed in
     *   [UnconditionalAcl.readableWithClientScopes], regardless of end-user consent.
     */
    fun canBeReadByClient(consentedScopes: List<String>, clientScopes: List<String>): Boolean =
        (acl.consent.readableByClient && (acl.consent.scope == null || acl.consent.scope in consentedScopes)) ||
                clientScopes.any { it in acl.unconditional.readableWithClientScopes }

    /**
     * Return true if a client can write this claim given the [consentedScopes] and [clientScopes].
     *
     * Access is granted through either path:
     * - **Consent path**: [ConsentAcl.writableByClient] is true AND either no consent scope
     *   is configured on this claim, or the end-user has consented to it.
     * - **Unconditional path**: the client holds any scope in [clientScopes] listed in
     *   [UnconditionalAcl.writableWithClientScopes], regardless of end-user consent.
     */
    fun canBeWrittenByClient(consentedScopes: List<String>, clientScopes: List<String>): Boolean =
        (acl.consent.writableByClient && (acl.consent.scope == null || acl.consent.scope in consentedScopes)) ||
                clientScopes.any { it in acl.unconditional.writableWithClientScopes }
}

enum class ClaimOrigin(val value: String) {
    OPENID_CONNECT("openid"),
    CUSTOM("custom")
}
