name: Build SympAuthy native image

env:
  GRAALVM_DISTRIBUTION: 'mandrel'

on:
  workflow_call:

jobs:
  build:
    name: Build SympAuthy native image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Create sympauthy-flow directory into resources
        run: mkdir -p server/src/main/resources/sympauthy-flow

      - name: Install sympauthy-flow into resources
        uses: actions/download-artifact@v8
        with:
          name: sympauthy-flow-dist
          path: server/src/main/resources/sympauthy-flow

      - name: Extract Java version from build script
        id: java-version
        run: |
          VERSION=$(grep -oP 'JavaVersion\.VERSION_\K[0-9]+' server/build.gradle.kts)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: wrapper

      - name: Setup Graalvm for JDK ${{ steps.java-version.outputs.version }}
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ steps.java-version.outputs.version }}
          distribution: ${{ env.GRAALVM_DISTRIBUTION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image
        run: gradle nativeCompile

      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: sympauthy-binary
          path: build/native/nativeCompile/sympauthy
