name: Build SympAuthy flow

on:
  workflow_call:

jobs:
  build:
    name: Build SympAuthy flow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'sympauthy/sympauthy-flow'
          ref: ${{ github.ref_name }}

      - name: Setup Node version configured in .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install node dependencies
        run: npm install

      - name: Build sympauthy-flow to be served on /flow by the server
        run: npm run build-only -- --base=/flow/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sympauthy-flow-dist
          path: dist

