name: Deploy changes of the develop every night.

env:
  JAVA_VERSION: 21
  GRAALVM_DISTRIBUTION: 'mandrel'

on:
  push:
    branches-ignore:
    - main

jobs:
  build:
    uses: ./.github/workflows/build-native.yml
