name: Deploy changes of the develop every night.

on:
  push:
    branches-ignore:
    - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-flow.yml
#  build:
#    uses: ./.github/workflows/build-native.yml
#
#  publish:
#    name: Build & Push SympAuthy docker image to GitHub Container Registry
#    needs: [build]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: docker/setup-buildx-action@v3
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Retrieve native image from cache
#        uses: actions/download-artifact@v4
#        with:
#          name: sympauthy-binary
#          path: .github/docker/arch
#
#      - name: Build & Push SympAuthy docker image
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          context: .github/docker/arch
#          tags: ghcr.io/sympauthy/sympauthy:latest-nightly
