name: Publish changes on develop every night

on:
  # Automatic nightly at 23:45 PM UTC
  schedule:
    - cron: '45 23 * * *'
  # Allow manually triggering nightly from the web interface
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish_nightly:
    uses: sympauthy/sympauthy/.github/workflows/publish-develop.yml@develop
    with:
      ref: develop
