name: Deploy changes of the develop every night.

on:
  push:
    branches-ignore:
    - main

permissions:
  contents: read
  packages: write

jobs:
  has_changed:
    name: Check if sympauthy has changed today.
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.has_changed.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - id: has_changed
        run: |
          export TODAY_DATE=$(date +'%Y-%m-%d')
          export COMMIT_DATE=$(git log -1 --date=format:"%Y-%m-%d" --format="%ad")
          if [ "$TODAY_DATE" != "$COMMIT_DATE" ]; then
            echo "sympauthy has changed today."
            echo "result=1" >> "$GITHUB_OUTPUT"
          else
            echo "sympauthy has not changed today. Last commit on $COMMIT_DATE"
            echo "result=0" >> "$GITHUB_OUTPUT"
          fi

  build_flow:
    needs: [has_changed]
    if: needs.has_changed.outputs.result == '1'
    uses: ./.github/workflows/build-flow.yml

  build_native_image:
    needs: [build_flow]
    uses: ./.github/workflows/build-native.yml

  publish:
    name: Build & Push SympAuthy docker image to GitHub Container Registry
    needs: [build_native_image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve native image from cache
        uses: actions/download-artifact@v4
        with:
          name: sympauthy-binary
          path: .github/docker/arch

      - name: Build & Push SympAuthy docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .github/docker/arch
          tags: ghcr.io/sympauthy/sympauthy:latest-nightly
