name: Deploy changes of the develop every night.

env:
  JAVA_VERSION: 17
  GRAALVM_DISTRIBUTION: 'mandrel'

on:
  push:
    branches-ignore:
    - main

jobs:
  build:
    name: Build sympauthy native image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Setup Graalvm for JDK ${{ env.JAVA_VERSION }}
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.GRAALVM_DISTRIBUTION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: gradle jibDockerBuild
