name: Deploy changes of the develop every night.

on:
  push:
    branches-ignore:
    - main

permissions:
  contents: read
  packages: write

jobs:
  today:
    name: Today
    runs-on: ubuntu-latest
    outputs:
      today: ${{ steps.set_today.outputs.today }}
    steps:
      - id: set_today
        run: echo today="$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"

  has_changed:
    name: Check if sympauthy has changed today.
    needs: [today]
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.has_changed.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - id: has_changed
        uses: ./.github/actions/has_changed
        with:
          name: sympauthy
          today: ${{ jobs.today.outputs.today }}

  has_flow_changed:
    name: Check if sympauthy-flow has changed today.
    needs: [today]
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.has_changed.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'sympauthy/sympauthy-flow'
          ref: ${{ github.ref_name }}
          path: sympauthy-flow
      - id: has_changed
        uses: ./.github/actions/has_changed
        with:
          name: sympauthy
          today: ${{ jobs.today.outputs.today }}
          path: sympauthy-flow

  build_flow:
    needs: [has_changed, has_flow_changed]
    if: needs.has_changed.outputs.result == '1' || needs.has_flow_changed.outputs.result == '1'
    uses: ./.github/workflows/build-flow.yml

  build_native_image:
    needs: [build_flow]
    uses: ./.github/workflows/build-native.yml

  publish:
    name: Build & Push SympAuthy docker image to GitHub Container Registry
    needs: [today, build_native_image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve native image from cache
        uses: actions/download-artifact@v4
        with:
          name: sympauthy-binary
          path: .github/docker/arch

      - name: Build & Push SympAuthy docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .github/docker/arch
          tags: |
            ghcr.io/sympauthy/sympauthy-nightly:${{ jobs.today.outputs.today }}
            ghcr.io/sympauthy/sympauthy-nightly:latest
