name: Build & Push SympAuthy docker image to GitHub Container Registry

env:
  JAVA_VERSION: 21
  GRAALVM_DISTRIBUTION: 'mandrel'

on:
  workflow_call:
    inputs:
      image:
        description: Name of the produced docker image (including registry).
        type: string
        required: true
      tag:
        description: Tag of the produced docker image.
        type: string
        required: true
      arch:
        description: Architecture to build the docker image for.
        type: string
        required: true

jobs:
  publish:
    name: Build & Publish native image for ${{ inputs.arch }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        name: Generate Docker metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image }}
          tags: type=raw,value=${{ inputs.tag }}-${{ inputs.arch }}

      - id: build
        name: Build and push by digest
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./.github/docker/Dockerfile
          platforms: linux/${{ inputs.arch }}
          labels: ${{ steps.meta.outputs.labels }}
