name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Run tests on all projects
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - run: ./gradlew test --no-daemon
